os: osx
language: csharp
install:
- nuget restore ./GLTFSerialization/GLTFSerialization.sln
- sudo python2 ./scripts/install-unity.py --package Unity 2017.4.16f1
before_script:
- sudo chmod -R a+rwx /Applications/Unity
script:
- msbuild ./GLTFSerialization/GLTFSerialization.sln /t:GLTFSerialization /p:TargetFramework=net35
- "./scripts/build-unity-project-and-run-tests.sh"

