sudo: required
language: csharp
env:
  global:
  - BUILD_NAME=UnityGLTF
  - PROJECT_PATH="UnityGLTF"
  - UNITY_VERSION=2018.4.14f1
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_98a45b338031_key -iv $encrypted_98a45b338031_iv
  -in ./scripts/Unity_v2018.x.ulf.enc -out ./Unity_v2018.x.ulf -d
- export UNITY_LICENSE_CONTENT=`cat Unity_v2018.x.ulf`
- rm Unity_v2018.x.ulf
- docker pull $IMAGE_NAME
install:
- nuget restore ./GLTFSerialization/GLTFSerialization.sln
- msbuild ./GLTFSerialization/GLTFSerialization.sln /t:GLTFSerialization /p:TargetFramework=net35
- chmod -R +rwx ./scripts/*
- chmod -R +rwx ./UnityGLTF/www/*
- chmod +rwx ./UnityGLTF/www/glTF-Asset-Generator/Output/Positive/Manifest.json
# - chmod -R a+rwx /Applications/Unity
jobs:
  include:
  - stage: test
    script: "./scripts/docker_test.sh"
    env: TEST_PLATFORM=editmode IMAGE_NAME=gableroux/unity3d:$UNITY_VERSION
  - stage: test
    script: "./scripts/docker_test.sh"
    env: TEST_PLATFORM=playmode IMAGE_NAME=gableroux/unity3d:2018.4.14f1
  - stage: build
    env: BUILD_TARGET=StandaloneLinux64 IMAGE_NAME=gableroux/unity3d:2018.4.14f1
    script: "./scripts/docker_build.sh"
  - stage: build
    env: BUILD_TARGET=StandaloneOSX IMAGE_NAME=gableroux/unity3d:2018.4.14f1-mac
    script: "./scripts/docker_build.sh"
  - stage: build
    env: BUILD_TARGET=StandaloneWindows64 IMAGE_NAME=gableroux/unity3d:2018.4.14f1-windows
    script: "./scripts/docker_build.sh"